### ISSUE TITLE
Support daemonset update without delete / create

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#136]
On GKE clusters, we can `kubectl apply` changes to existing deployments and the differences are automatically applied to all effected objects.

On our K8s cluster, we have been deleting and recreating daemonsets to deploy new versions because `kubectl apply`  does not work in the same way.

We need a reliable way of deploying incremental updates without taking the entire platform offline first.

**Comment by nkinkade** [comment]
Is this true still, or is this something we observed a long time ago, with some older version of k8s, and just assume it is still true?

**Comment by stephen-soltesz** [comment]
We definitely observed in last Aug. We need to confirm that it works now or find a work around to deleting and recreating daemonsets before deploying to production.

**Comment by stephen-soltesz** [comment]
Working with @gfr10598 we confirmed that `kubectl apply -f .../ndt.yml` does not work as it would on GKE. In particular, `kubectl describe ds ndt` reported the updated container version, however the versions running were still the old versions. It seems that k8s does not automatically restart the container.

**Comment by nkinkade** [comment]
We believe this is the result of using a default `updateStrategy` of `OnDelete`, instead of `RollingUpdate`. @pboothe has verified in mlab-sandbox that explicitly setting an `updateStrategy=RollingUpdate` on the NDT DaemonSet and then using `kubectl apply -f` both updates the DS configuration and also kills and relaunches all associated pods (creates a new ReplicaSet, I believe).

@pboothe is working on a larger NDT DaemonSet PR that will include RollingUpdates, and I have merged PR #145 that explicitly configures RollingUpdates for all of our DaemonSets and Deployments.

@stephen-soltesz: I believe this issue is resolved. If you believe this too, could you close this issue?

**Comment by stephen-soltesz** [comment]
Thank you!
