### ISSUE TITLE
scamper is trying to run on nodes that it should not (like the master nodes)

### ISSUE THREAD

**Issue by yachang** [m-lab/k8s-support#149]

**Comment by yachang** [comment]
The scamper deployment, at least on staging, needs a NodeSelector to prevent it trying to run on the k8s-prometheus node.

scamper-tcf48 1/2 CrashLoopBackOff 240 20h 10.0.0.20 k8s-prometheus

**Comment by nkinkade** [comment]
@yachang: I believe I already corrected this issue here:

https://github.com/m-lab/k8s-support/pull/145/files#diff-6f678f6ab6746ef4b3dc81007cbad9d9R19

I'm sorry I didn't communicate the change I had made to you before.

This PR was already merged. If you believe that this fixed the issue, would you close this issue?
