### ISSUE TITLE
data-loss: Pusher should have time to upload data before SIGKILL from k8s

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#354]
Right now, pusher's default -sigterm_wait_time is 150s -- this was probably meant to mirror ndt's terminationGracePeriodSeconds: 150 setting.  Pusher starts to upload after that period, but k8s will send SIGKILL after waiting terminationGracePeriodSeconds. For NDT I suspect that there is no time to upload any data and for the other experiments, I suspect that pusher is getting SIGKILL before it ever gets a chance to upload the data.

This could mean data loss of the last two hours or <50MB of data.

**Comment by stephen-soltesz** [comment]
Short term proposal:

* extend NDT's terminationGracePeriodSeconds to 3m
* set pusher's -sigterm_wait_time to 2m, this allows mlab-ns time to update and pusher 1m to upload.
* add terminationGracePeriodSeconds: 3m for other experiments so we don't have to add a new parameter to plumb through to pusher conditionally right now.

Long term proposal:

* make the pusher -sigterm_wait_time conditional on the experiments terminationGracePeriodSeconds setting.

**Comment by stephen-soltesz** [comment]
#355 completes the short term proposal.

**Comment by stephen-soltesz** [comment]
Re-opening because only the "short" term solution was addressed in #355. The issue should remain open for a better solution, and confirmation that the short-term solution is actually wai.

**Comment by nkinkade** [comment]
@stephen-soltesz: I'm looking through old issues for stragglers.  This is 6 months old with P1, backlog labels. Is this still a concern?

**Comment by stephen-soltesz** [comment]
What I think I was referring to in the "long term solution" was connecting the pusher parameter to the termination grace time via jsonnet variables or similar. Right now those values are independent, they should not be.

**Comment by nkinkade** [comment]
Right now, we [manually override](https://github.com/m-lab/k8s-support/blob/master/k8s/daemonsets/experiments/ndt.jsonnet#L108) the value of `terminationGracePeriod` [in any DaemonSet ](https://github.com/m-lab/k8s-support/blob/master/k8s/daemonsets/experiments/neubot.jsonnet#L60)where we may want it, and it is set to 180s. The pusher container has a flag, [-sig_wait_term](https://github.com/m-lab/pusher/blob/master/pusher.go#L51), which is set to 120s.

If I understand what is going on in pusher, when pusher first receives a SIGTERM, it will begin to upload archives whether it has collected them for enough time, or size, or not, but it will continue to collect for a while longer. When the `-sig_wait_term` time happens it will stop collecting data altogether and start shipping as much of the remaining data to GCS as it can. So if it can't upload the remaining data in the last 60s (180s - 120s), that data will be lost.

Are you suggesting here that `terminationGracePeriod` should be 180s for every single experiment, and not hardcoded into each DaemonSet manifest, and that the value for `-sig_wait_term` should be the value of `terminationGracePeriod` - 60s? And that this should all be done using variables and math instead of hardcoding things anywhere?

**Comment by stephen-soltesz** [comment]
Right -- I don't have a specific implementation in mind, but basically rather than two independent constants, have one constant and two dependent users with some math.

**Comment by nkinkade** [comment]
I believe this issue is resolved by merged PR #466.
