### ISSUE TITLE
Prometheus on platform cluster takes too long to start up

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#371]
When we deploy changes to the prometheus configuration for the platform cluster we typically see an unclean shutdown followed by a slow startup as the server rescans all tsdb files for consistency.

It should be possible to give the prometheus server time to shutdown cleanly before k8s kills it.

**Comment by nkinkade** [comment]
This is starting to look like it is not an issue with the kubelet killing Prometheus being it is taking to long to shut down, or otherwise an issue with Prometheus not shutting down cleanly. I tested shutting down the Prometheus pod in mlab-oti, and it shut itself down and the new pod started in less than, say, 10 or 15 seconds. The current `terminationGracePeriod` is 30s for the Prometheus pod, and it certainly didn't take longer than 30s for the old pod to shutdown and the new pod to start.

It appears that ingesting the WAL is just a normal part of starting up Prometheus. And [there are](https://github.com/prometheus/tsdb/issues/611) other [people complaining](https://github.com/prometheus/prometheus/issues/6322) of slow startups as well.
 
In one issue [Brian Brazil mentions that 1.5G index files seem kind of big](https://github.com/prometheus/tsdb/issues/611#issuecomment-497251638). I just looked at one of our block index files and it is 14.6GB.

Prom a [PromCon talk slidedeck](https://promcon.io/2019-munich/slides/containing-your-cardinality.pdf) I found this:

> A single Prometheus can handle >10,000,000 series in memory
> ● Startup can take 15+ minutes

We've currently got around 4,500,000 series, and startup times seem to be around 5m. 

It's not clear to me at the moment how we can improve startup times without trying to modify which metrics we collect and how much of them.

**Comment by nkinkade** [comment]
[Brian Brazil says this about Prometheus 2.15.0](https://www.robustperception.io/new-features-in-prometheus-2-15-0):

> There have also been performance improvements in WAL replay (i.e. startup time), and the space taken by the WAL is now considered for size-based retention.

Seems like a first shot in helping to improve startup times should be to upgrade from 2.14.0 to 2.15.0. I will start this process now.

**Comment by nkinkade** [comment]
We had an unexpected opportunity yesterday to observe how fast Prometheus starts up with v2.16.0. The Prometheus node got automatically rebooted by CoreOS for an OS upgrade. The events were timed like this:

23:35:51 - kubelet stopped for reboot
23:35:55 - k8s reports Pod finished
\- Reboot
23:37:15 - kubelet starts after reboot
23:37:51 - First Prometheus startup message
23:41:23 - msg="Server is ready to receive web requests."

**5:29**: interval from the time k8s reports the pod finished and when Prometheus reported it was ready to serve web requests again.

To see how long Prometheus would be unavailable in the event of a pod restart (instead of a reboot), I manually deleted the pod in production with these timings:

16:33:48 - Manually deleted pod
16:34:03 - First Prometheus startup message
16:38:26 - msg="Server is ready to receive web requests."

**4:38**: interval between time pod deleted and Prometheus was ready to serve web requests again.

This seems to indicate that our current alert threshold of 4m is too low. However, there alert has this comment:

> The threshold for being down is 4m, such that this alert will fire slightly before the alerts for missing individual DaemonSet metrics (and can inhibit those).

And we are in fact [currently inhibiting DaemonSet missing alerts if the scrape job is down](https://github.com/m-lab/prometheus-support/blob/master/config/federation/alertmanager/config.yml.template#L82).

**Comment by nkinkade** [comment]
This issue is not resolved; Prometheus still takes too long to startup. It's not clear that there is much we can do about this at the moment. It seems to be a known limitation for very busy Prometheus instance (WAL replay being the major culprit. However, the alert that used to fire due to this slow startup is now resolved by simply increasing the time threshold on the alert in PR m-lab/prometheus-support#636.

@stephen-soltesz: Would you like to leave this issue open or close it for now?

**Comment by stephen-soltesz** [comment]
I still think we need _an_ issue open. The problem that remains is that restarts of the prometheus server result in long blindspots in our monitoring. This impacts our visibility but also mlab-ns. If we cannot continue to solve this with a single prometheus instance, then this may mean that the problem is just harder than we hoped. For example, it may be time to run two prometheus instances that provide redundancy. It's also possible that the blind spot concern will be greatly reduced with the eventual migration to locate v2.

**Comment by nkinkade** [comment]
We may as well leave this issue open to track the issue. For now, with a single Prometheus instance it would [appear that slow startup times are a known issue for busy Prometheus instances](https://github.com/prometheus/prometheus/issues/6526).

**Comment by nkinkade** [comment]
I just noticed this in the Prometheus [change logs for 2.30.0](https://github.com/prometheus/prometheus/releases/tag/v2.30.0):

> [FEATURE] experimental TSDB: Snapshot in-memory chunks on shutdown for faster restarts. Behind --enable-feature=memory-snapshot-on-shutdown flag.

Once that feature is no longer experimental, we should look at it to see whether it helps this issue.

**Comment by nkinkade** [comment]
This new flag is now enabled on the production instance of Prometheus in the platform cluster. The most recent startup time with this flag enabled was ~1m30s, down from ~3m30s on the previous startup. I believe that this is now reasonable enough that we can safely close this issue. @stephen-soltesz: if you agree, would you close this issue? Since you opened it, I would rather that you also close it, just to be 100% sure that the my your criteria are aligned with mine. Thanks.

**Comment by stephen-soltesz** [comment]
That's pretty good, I agree.

**Comment by valyala** [comment]
I'd recommend trying [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) instead of Prometheus. It should have much smaller startup times (e.g. seconds vs minutes), because it [doesn't use WAL]( https://valyala.medium.com/wal-usage-looks-broken-in-modern-time-series-databases-b62a627ab704). It also recovers almost instantly from unclean shutdown such as OOM kill or `kill -9`. It is protected from data corruption on unclean shutdown - only the data collected during the last second can be lost in this case. VictoriaMetrics also usually needs multiple times smaller amounts of RAM and disk space than Prometheus on identical workloads - see [this article](https://valyala.medium.com/prometheus-vs-victoriametrics-benchmark-on-node-exporter-metrics-4ca29c75590f).

I'm the main developer of VictoriaMetrics, so I'll be happy to help you with any questions.
