### ISSUE TITLE
node mlab/type=physical (not "platform")

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#372]
Currently, setup_k8s.sh and the flannel-platform.jsonnet configurations apply the node label `mlab/type=platform` for physical nodes, to distinguish them from the `mlab/type=cloud` nodes that run in VMs.

I suggest that we use different names to distinguish "physical" nodes from "virtual" nodes.

* `mlab/type=physical` (instead of platform)
* `mlab/type=virtual` (instead of cloud)

Because this label is used to assign network configurations, we must take care when changing it.

Following steps for physical change:

1. Add a new label to all nodes. i.e. `tmp/type=physical` using kubectl.
2. Commit changes to k8s-support:

   * Update network configs to refer to `tmp/type=physical`
   * Update setup_k8s.sh to assign preferred label `mlab/type=physical`

3. Deploy to production.
4. Add / overwrite the `mlab/type=physical` label on all nodes.
5. Commit changes to k8s-support:

   * Update network configs to refer to `mlab/type=physical`

6. Deploy to production.
7. Remove any remaining node labels with `tmp/type=physical`.

Obviously, if there's a simple sequence of steps, we should probably do that instead.

```
$ kubectl label node --overwrite=true mlab4.lga1t.measurement-lab.org mlab/type=physical
```

**Comment by nkinkade** [comment]
A couple observations as I think through this:
* More than just the flannel configs rely on the `mlab/type` node label. All experiments use it as `nodeSelector`, as well as the `update-agent` and `utilization` DaemonSets.
* In the flannel DaemonSets the word "platform" is also used in the name of the DaemonSet and also as part of the pod `selector` field. In k8s, as I understand it, the `selector` field of a DaemonSet or Deployment is immutable, which means that we cannot just change values in the `selector` field and then attempt to apply it to the cluster. I believe it will fail to apply with an error.

A slightly modified deployment strategy might be:
1. Make every necessary change in this repository.
2. Manually add the node label `tmp/type=physical` to every node in the project.
3. Manually modify (`kubectl edit`) the `nodeSelector` of all necessary DaemonSets in the project (most all of them), and wait for the rollouts to complete.
4. Relabel (overwrite) the `mlab/type` label to be `physical` instead of `platform` on every node.
5. Delete the flannel DaemonSets in the project. Then immediately:
6. Deploy the changes in this repo to the project (i.e., pushing to sandbox, or merging to master, or tagging repo).

I believe it is safe to delete the flannel DaemonSets, at least for a while. We don't use pod-to-pod communication, and deleting the DaemonSet doesn't seem to modify the running IP config for pods... maybe because flannel gets a default subnet lease that lasts 24 hours?

**Comment by nkinkade** [comment]
This is nearly done. sandbox and staging have already been converted and production is half of the way there, and should be completed sometime next Monday.

**Comment by nkinkade** [comment]
This transition is now complete in all projects. Closing.
