### ISSUE TITLE
uuid-annotator deployment is broken

### ISSUE THREAD

**Issue by pboothe** [m-lab/k8s-support#411]
Just bumping the version didn't work.  This has dragged on for a week.  Creating an issue to centralize knowledge.

**Comment by nkinkade** [comment]
The underlying cause of the uuid-annotator problems was that the tcp-info container was in an ImagePullBackoff state because no image was tagged 1.5.0 in DockerHub. The repository was tagged 1.5.0, but the DockerHub build had failed due to a transitory issue fetching a resource from Github. I restarted the build on DockerHub. Once it completed all pods cleared up in sandbox.

Closing this issue.
