### ISSUE TITLE
Ubuntu nodes need to be load tested

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#415]
Before we graduate Ubuntu nodes from sandbox, they need to be load tested to be sure they are at least as performant as CoreOS.

**Comment by nkinkade** [comment]
# CoreOS
This morning is reverted mlab[2-4].lga0t back to running CoreOS. From both mlab2 and mlab4 I ran the following (which launches tests against the mlab3 node):

```
# docker run -w /root/bin --net=host -it soltesz/phatbox:10 ./run.sh 10 150 10
```

`run.sh` was launched at `2020-04-14T18:07:40` on mlab2 and `2020-04-14T18:07:38` on mlab4.

Metrics collection from the mlab3 machine fell over at around 19:23, shortly after this phase began:

```
2020-04-14T19:21:26+00:00 Starting 130 ...
```

[Benchmark results for this period](https://grafana.mlab-sandbox.measurementlab.net/d/WYiYLa1Zk/soltesz-benchmark?orgId=1&from=1586887335066&to=1586895215066&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-left_deployment=host&var-left_machine=mlab2&var-center_deployment=ndt&var-center_machine=mlab3&var-right_deployment=host&var-right_machine=mlab4&var-site=lga0t).

**Comment by nkinkade** [comment]
# Ubuntu
After the CoreOS tests completed I reconverted mlab[2-4].lga0t to Ubuntu, and then ran the same steps as for CoreOS.

`run.sh` was launched at `2020-04-14T20:24:20` on mlab2 and `2020-04-14T20:24:19` on mlab4.

Metrics collection never fell over.

[Benchmark results for this period](https://grafana.mlab-sandbox.measurementlab.net/d/WYiYLa1Zk/soltesz-benchmark?orgId=1&from=1586895589288&to=1586902949288&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-left_deployment=host&var-left_machine=mlab2&var-center_deployment=ndt&var-center_machine=mlab3&var-right_deployment=host&var-right_machine=mlab4&var-site=lga0t).

**Comment by nkinkade** [comment]
[Side by side comparison of CoreOS and Ubuntu](https://grafana.mlab-sandbox.measurementlab.net/d/WYiYLa1Zk/soltesz-benchmark?orgId=1&from=1586887282631&to=1586903282631&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-left_deployment=host&var-left_machine=mlab2&var-center_deployment=ndt&var-center_machine=mlab3&var-right_deployment=host&var-right_machine=mlab4&var-site=lga0t).

The two performed similarly, with some notable differences:
* [Network metrics](https://grafana.mlab-sandbox.measurementlab.net/d/WYiYLa1Zk/soltesz-benchmark?orgId=1&from=1586887282631&to=1586903282631&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-left_deployment=host&var-left_machine=mlab2&var-center_deployment=ndt&var-center_machine=mlab3&var-right_deployment=host&var-right_machine=mlab4&var-site=lga0t&fullscreen&panelId=47) appear [significantly more stable](https://grafana.mlab-sandbox.measurementlab.net/d/WYiYLa1Zk/soltesz-benchmark?orgId=1&from=1586887282631&to=1586903282631&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-left_deployment=host&var-left_machine=mlab2&var-center_deployment=ndt&var-center_machine=mlab3&var-right_deployment=host&var-right_machine=mlab4&var-site=lga0t&fullscreen&panelId=55) under Ubuntu for some reason.
* [OpenFDs on mlab3 under Ubuntu were drastically lower under Ubuntu](https://grafana.mlab-sandbox.measurementlab.net/d/WYiYLa1Zk/soltesz-benchmark?orgId=1&from=1586887282631&to=1586903282631&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-left_deployment=host&var-left_machine=mlab2&var-center_deployment=ndt&var-center_machine=mlab3&var-right_deployment=host&var-right_machine=mlab4&var-site=lga0t&fullscreen&panelId=39).
* [`% sec/sec` disk I/O was substantially lower under Ubuntu on mlab3](https://grafana.mlab-sandbox.measurementlab.net/d/hU5aYvaWz/k8s-site-overview?orgId=1&from=1586886429498&to=1586902526699&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-site=lga0t&var-node=mlab3&var-pod=ndt&var-container=All&fullscreen&panelId=30).
*  ["Pod CPU Usage" was substantially *higher* for certain containers under Ubuntu](https://grafana.mlab-sandbox.measurementlab.net/d/hU5aYvaWz/k8s-site-overview?orgId=1&from=1586887198916&to=1586902526793&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-site=lga0t&var-node=mlab3&var-pod=ndt&var-container=All&fullscreen&panelId=15).

**Comment by nkinkade** [comment]
@stephen-soltesz: I believe these results are ready for your review when you have time.

**Comment by stephen-soltesz** [comment]
That's fascinating.

The open fds difference is strangest to me. Is all the data being collected?

I can imagine that a different kernel could behave differently wrt disk i/o scheduling and cpu utilization for similar operations. But, why would there be so many more FDs in core os attributed to the packet headers?

The increased CPU load could create a new ceiling / bottleneck where we used to hit RAM first. There are examples from other services too, though PH is the biggest. Though, if we can sustain 300 connections, that's still higher than the highwater mark we want to support. So, it could be okay to proceed while we continue to investigate.

So, my only remaining reservation is whether the data is collected end to end. Are the open FDs indicitive of more successful save events? Could PH on Ubuntu possibly be missing data? Since the CPU load is higher it's _plausible_ that a) pcap collection is more expensive and as a result b) some packets are being missed. But, I wouldn't think that would change the FD counts...

Also @nkinkade, for future reference, notice the change in [Read I/O][readio] as load increases. My understanding is that this is an indication of system overload: as the buffer cache is evicted to provide more RAM for the system, processes _using_ that cache need to start reading it from disk over and over.

[readio]: https://grafana.mlab-sandbox.measurementlab.net/d/rJ7z2Suik/k8s-site-overview?orgId=1&from=1586887282631&to=1586903282631&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-site=lga0t&var-node=All&var-pod=All&fullscreen&panelId=187

**Comment by stephen-soltesz** [comment]
The question that came from in person discussion with @nkinkade @gfr10598 @mattmathis @pboothe and I is, how do we qualify our data on the new platform. The short answer is "using a canary" and then some analysis of the BQ data. By analogy, this is similar to the entry and exit criteria of the new platform migration. However, we have no automated analysis.

As well, there are performance questions about the ubuntu system that we should continue to investigate:

* source of the ~60% CPU overhead on a heavily loaded system
* fast-path sources of acceptance criteria to speed the canary-to-prod promotion.

**Comment by pboothe** [comment]
Increased IO efficiency would lead to fewer open files. Pusher doesn't keep files open after it reads them as of https://github.com/m-lab/pusher/pull/74 .

**Comment by pboothe** [comment]
So as long as pusher pushed the about same number of files from each server, what we are seeing is just better disk IO scheduling in Linux 5.4

**Comment by nkinkade** [comment]
Closing this issue. Consensus is that the extra CPU load introduced by moving to Ubuntu need to be further investigated, but is not blocking in migrating to Ubuntu.
