### ISSUE TITLE
Make sure kubelet start depends on successful config application

### ISSUE THREAD

**Issue by pboothe** [m-lab/k8s-support#428]
Make sure kubelet start depends on successful config application.

**Comment by nkinkade** [comment]
I believe that this issue is resolved by #465. It's been a couple months, and I'm hazy on the exact details of why this issue was opened, but I did find this in [the Ops Tactical notes](https://docs.google.com/document/d/1RTCW4agYQ9t24ebA-pgtzBVeElsUX9Z7PdzNT6ndpmc/edit#heading=h.2641pz5990of) from the day this issue was opened:

```
* mlab4.hnd01 is not booting (in staging)
    *TODO(kinkade) will investigate
    *Config on node did not complete successfully
    * kubectl join should not succeed unless node is fully configured.
    * https://github.com/m-lab/k8s-support/issues/428
```

My _recollection_ is that maybe `curl` failed to download one of the kubelet configuration files or only partially downloaded it without actually completely failing (if that is even possible?), and so [adding of node labels](https://github.com/m-lab/k8s-support/blob/master/node/setup_k8s.sh.template#L74) didn't happen properly, because the file didn't exist. However, now, [those  kubelet](https://github.com/m-lab/epoxy-images/pull/169/files#diff-0a8e774515404f162c8c1c8dbb9a4609R150) [config files](https://github.com/m-lab/epoxy-images/pull/169/files#diff-0a8e774515404f162c8c1c8dbb9a4609R157) are baked into the ePoxy Ubuntu images.

I can't really see anything in [setup_k8s.sh](https://github.com/m-lab/k8s-support/blob/master/node/setup_k8s.sh.template) that could reasonably fail, causing a node to join the cluster but with bad/improper configs.

Closing. We can reopen if we find a specific use case that this issue applies to which I've missed.
