### ISSUE TITLE
Create script to create epoxy-private network firewall rules

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#45]
Right now the k8s-master joins the epoxy-private network and requires specific set of publicly open ports so the k8s master can start and so nodes can join it.

So far we have created these rules manually using the GCP web console. That is bad.

Create a script to configure these firewalls.

**Comment by nkinkade** [comment]
@stephen-soltesz: I believe this issue is resolved. The [bootstrap_platform_cluster.sh script](https://github.com/m-lab/k8s-support/blob/master/manage-cluster/bootstrap_platform_cluster.sh#L418) creates the firewall rules allowing ePoxy to contact the cluster. And the `epoxy-private-network` network no longer exists.
